### ISSUE TITLE
3.2.1 does not process plugins in windi.config.js

### ISSUE THREAD

**Issue by multics** [windicss/svelte-windicss-preprocess#101]
for example: to use scroll-snap plugin, add following is good enough.
```
 module.exports = {
 plugins: [
    require('windicss/plugin/scroll-snap'),
  ]
}
```

Since 3.2.1, plugins are not loaded correctly.

FYI: 3.2.0 works perfectly.

**Comment by alexanderniebuhr** [comment]
fix is in works.. eta 1-2 day .. sorry for that.. just stick to 3.2.0 for now

**Comment by alexanderniebuhr** [comment]
check https://github.com/windicss/svelte-windicss-preprocess/releases/tag/v3.3.0

**Comment by alexanderniebuhr** [comment]
@multics does it work with the latest update?
