### ISSUE TITLE
Debug messages still show even when silent is set to true

### ISSUE THREAD

**Issue by TedMeftah** [windicss/svelte-windicss-preprocess#114]
I noticed in the current version these debug messages still show up even when the `silent` flag is set to true:

```
[DEBUG] initialisationPending
[DEBUG] initialisationDone
[DEBUG] initialisationDone
```
I don't think this is intended, and I think the issue is due to a missing check on these two line:

https://github.com/windicss/svelte-windicss-preprocess/blob/e4771a93f1a946b69fd24c25328d283db3084964/src/index.ts#L364

https://github.com/windicss/svelte-windicss-preprocess/blob/e4771a93f1a946b69fd24c25328d283db3084964/src/index.ts#L373

**Comment by alexanderniebuhr** [comment]
yes, check is missing, feel free to make a PR
