### ISSUE TITLE
Styles in style tag works even if it's commented out

### ISSUE THREAD

**Issue by onderbakirtas** [windicss/svelte-windicss-preprocess#12]
Hello there. I've met with this brilliance yesterday and encountered a weird issue.

When I comment out my `style` section like this, the code still works and styles get applied:
```svelte
<!-- <style lang="postcss">
  nav {
    border: 10px solid black;
    @apply bg-red-200;
  }
</style> -->
```

But if I comment out my code like this, styles doesn't get applied as intended:
```svelte
<style>
  /* nav {
    border: 10px solid black;
    @apply bg-red-200;
  } */
</style>
```

It doesn't matter if I change the `lang` attribute of the `style` tag, or even omitting it. The issue is bound to Windi CSS since removing `preprocess` codes from **rollup.config.js**, everything works as expected.

I'm willing to help to fix this issue if any tests and/or recoding to do. Thanks a lot for this plugin.

**Comment by voorjaar** [comment]
https://github.com/windicss/svelte-windicss-preprocess/commit/d7cd59052fbbac637cf307035424e15de46309f3 should fix this. And also added some tests https://github.com/windicss/svelte-windicss-preprocess/commit/d3c24bc802e688859445b2b4ddf6e96813aa9104. Feel free to contribute.
