### ISSUE TITLE
Option to disable preflight.

### ISSUE THREAD

**Issue by anikraj1994** [windicss/svelte-windicss-preprocess#120]
I'm developing a single component that will be part of a larger web app. How can I disable the preflight CSS normalisations and just generate the classes which I actually use? Thank you.

**Comment by alexanderniebuhr** [comment]
currently that is not supported. I add this as an enhancement to the roadmap

**Comment by anikraj1994** [comment]
Thank you.

**Comment by alexanderniebuhr** [comment]
will go live the next days with v4. 3151e05b4aa48b65b98d8bd7fe8c01481aad1094
docs will be at [integration guide](https://windicss.org/integrations/svelte.html)
