### ISSUE TITLE
preflight does not work as expected, missing normalizecss

### ISSUE THREAD

**Issue by alexanderniebuhr** [windicss/svelte-windicss-preprocess#14]
I have a strange issue, I am serving my Svelte App with esbuild serve (shouldn't be a problem here, am more than happy to try things with this setup for you), but if I reload the first time it does look correct, site does work completely and is loaded fully, however if I am reloading a second time it does removes some styles, looks strange. Anytime I am changing any class it does work for the first reload, any reload after that is not working. Tried with both modes (...compile)

https://user-images.githubusercontent.com/45965090/108535725-eb899a00-72db-11eb-9068-f7f768d31820.mp4

**Comment by alesvaupotic** [comment]
I can confirm the behaviour, happens with Rollup and nollup, too.

**Comment by alexanderniebuhr** [comment]
I will have a look into the code later tonight. Might find something, and can help with a PR. Any new infos would be great to track here

**Comment by voorjaar** [comment]
Thank you. I believe the issue exists because every time you refresh, the preflight will be removed. And need to be added again. But it should not effect the build results. I am currently working on other projects, so hope you can fix this issue. Good luck.

**Comment by alexanderniebuhr** [comment]
@voorjaar I might found the typo, see PR (https://github.com/windicss/svelte-windicss-preprocess/pull/15)

Could we do an extra tag on the NPM package so others, like @alesvaupotic could test, if it works I think you might me able to merge.

**Comment by alesvaupotic** [comment]
Available for testing any time.

**Comment by alexanderniebuhr** [comment]
@alesvaupotic check if your preprocessor gets `process.env.NODE_ENV = 'development'`
My setup caused some issues so that the preprocessor did not get it at all, and had `undefined` for the windicss

**Comment by alesvaupotic** [comment]
I am on default Rollup config with adjusted the config files from README. It does not mention NODE_ENV anywhere.

**Comment by alexanderniebuhr** [comment]
You would need NODE_ENV as an `process.env.NODE_ENV` to work properly, please try and let us know if it fixes the problem. We are more than happy to update the README than.

**Comment by alesvaupotic** [comment]
I moved to Snowpack and it's fine. Will come back to Rollup setup later.

**Comment by alexanderniebuhr** [comment]
you should be able to set `process.env.NODE_ENV` in you package.json scripts, it shouldn't be special to Rollup or Snowpack. Have a look at https://www.npmjs.com/package/cross-env

**Comment by alesvaupotic** [comment]
Ok, dedicated some time to it. I think I got it right but how do I debug and confirm that NODE_ENV is passed correctly to WindiCSS? What happens is that it works quite nicely with changing classes in Svelte files, doing @apply changes and similar. It breaks (loses the normalize part) when I re-save a file without any changes to it, like two quick consecutive CTRL-S presses. Once I change something in classes and save the file, it comes back up correctly.

**Comment by alexanderniebuhr** [comment]
Logging should be live soon. Then you can change your config as following.  If you have any unexpected behavior, I will ask you to open new issue with information, so I can work on additional fixes.

@voorjaar how to trigger release for the logging?

```javascript
preprocess: require("svelte-windicss-preprocess").preprocess({
    silent: false, // <--- add this
    debug: true, // <--- add this
    config: 'tailwind.config.js',
    compile: false,
    prefix: "windi-",
    globalPreflight: true,
    globalUtility: true,
  }),
```

**Comment by alexanderniebuhr** [comment]
@alesvaupotic check https://github.com/windicss/svelte-windicss-preprocess/releases/tag/v2.1.5
will update readme later

**Comment by alesvaupotic** [comment]
After seeing the new logging messages, I was able to ajust my setup and can confirm it works as expected. Thanks!
