### ISSUE TITLE
colors in windi.config.js are not loaded with sveltekit

### ISSUE THREAD

**Issue by moisesbites** [windicss/svelte-windicss-preprocess#140]
I had installed windicss following https://windicss.org/integrations/svelte.html#sveltekit configuration page.

```JS
// svelte.config.js
import { windi } from 'svelte-windicss-preprocess';
import node from '@sveltejs/adapter-node';
import path from 'path';

/** @type {import('@sveltejs/kit').Config} */
const config = {
	preprocess: [windi({})],
	kit: {
		adapter: node(),
		// hydrate the <div id="svelte"> element in src/app.html
		target: '#svelte',
		hostHeader: 'X-Forwarded-Host',
		vite: {
			resolve: {
				alias: {
					$sto: path.resolve('./src/stores')
				}
			},
			server: {
				hmr: {
					protocol: 'ws',
					port: 3001
				}
			}
		}
	}
};

export default config;
``` 

```JS
// windi.config.js
import { defineConfig } from 'windicss/helpers';
import colors from 'windicss/colors';

export default defineConfig({
	darkMode: 'class', // or 'media'
	theme: {
		extend: {
			colors: {
				unica: '#9F3133',
				primary: {
					light: '#edcbc7',
					DEFAULT: '#9f3133',
					dark: '#4f1e1d'
				}
                         }
		}
	},
	variants: {},
	plugins: []
});
```

![image](https://user-images.githubusercontent.com/8934577/118340452-b7440500-b4e9-11eb-9c05-e2de8025f0fe.png)

But the colors are not working:
![image](https://user-images.githubusercontent.com/8934577/118340413-967baf80-b4e9-11eb-9c3c-c1df0ceb30c9.png)

**Comment by alexanderniebuhr** [comment]
yes you did not set any configuration to the windi function in svelte.config.js, set configPath in the Options of `windi` [see reference](https://windicss.org/integrations/svelte.html#options)

```
// svelte.config.js
import { windi } from 'svelte-windicss-preprocess';
import node from '@sveltejs/adapter-node';
import path from 'path';

/** @type {import('@sveltejs/kit').Config} */
const config = {
	preprocess: [windi({
configPath: "windi.config.js"
})],
	kit: {
		adapter: node(),
		// hydrate the <div id="svelte"> element in src/app.html
		target: '#svelte',
		hostHeader: 'X-Forwarded-Host',
		vite: {
			resolve: {
				alias: {
					$sto: path.resolve('./src/stores')
				}
			},
			server: {
				hmr: {
					protocol: 'ws',
					port: 3001
				}
			}
		}
	}
};

export default config;
```

**Comment by alexanderniebuhr** [comment]
for colors syntax check in VS Code follow the [issue](https://github.com/windicss/windicss-intellisense/issues/124)

**Comment by moisesbites** [comment]
Thank you very much. The colors are working now in the windi.config.js.

Maybe, because this information:
![image](https://user-images.githubusercontent.com/8934577/118364816-0a5c9d00-b568-11eb-93fe-1eddd90f4edd.png)

...would be good to put the configuration path of `windi.config.js` in the orientation ate the page https://windicss.org/integrations/svelte.html#sveltekit.
