### ISSUE TITLE
"hover" is not working in <style> in __layout.svelte

### ISSUE THREAD

**Issue by moisesbites** [windicss/svelte-windicss-preprocess#141]
Using `hover` in `__layout.svelte`, it is not working:
```JS
<slot />
<style windi:preflights:global>
	:root {
		font-family: 'Lato', 'Open Sans', 'Segoe UI', 'Roboto';
	}
  :global(a) {
		@apply text-secundary;
		@apply hover:text-primary;
	}
</style>
```

But, if I use in `index.svelte`, `hover` works fine:
```JS
<h1>Welcome to SvelteKit</h1>
<p>
	Visit <a href="https://kit.svelte.dev">kit.svelte.dev</a> to read the documentation
</p>

<style>
  a {
		@apply hover:text-primary;
	}
</style>
```

**Comment by alexanderniebuhr** [comment]
@moisesbites good catch. This is an serious bug, we need to fix.

Actually it has nothing todo with the file the style is placed.
It is caused by the `:global()` wrapper, you can try this by adding an `:global()` wrapper in `index.svelte` style, and it won't work.

For the time being and to provide an solution for you. I suggest one of the following workaround for now. In parallel I am working on a fix, which will land in v4.1. Hope this helps!

**Workaround 1** (make all styles in style tag global):

```svelte
<style global windi:preflights:global windi:safelist:gobal>
 a {
    @apply text-secundary hover:text-primary;
  }
</style>
```

**Workaround 2** (let svelte handle the global style, and move pseudoElement to rule)

```svelte
<style windi:preflights:global windi:safelist:gobal>
  :global(a) {
    @apply text-gray-200;
  }
  :global(a:hover) {
    @apply text-gray-900;
  }
</style>
```

**Comment by moisesbites** [comment]
> @moisesbites good catch. This is an serious bug, we need to fix.
> 
> Actually it has nothing todo with the file the style is placed.
> It is caused by the `:global()` wrapper, you can try this by adding an `:global()` wrapper in `index.svelte` style, and it won't work.
> 
> For the time being and to provide an solution for you. I suggest one of the following workaround for now. In parallel I am working on a fix, which will land in v4.1. Hope this helps!
> 
> **Workaround 1** (make all styles in style tag global):
> 
> ```svelte
> <style global windi:preflights:global windi:safelist:gobal>
>  a {
>     @apply text-secundary hover:text-primary;
>   }
> </style>
> ```
> 
> **Workaround 2** (let svelte handle the global style, and move pseudoElement to rule)
> 
> ```svelte
> <style windi:preflights:global windi:safelist:gobal>
>   :global(a) {
>     @apply text-gray-200;
>   }
>   :global(a:hover) {
>     @apply text-gray-900;
>   }
> </style>
> ```

@alexanderniebuhr Thank you for your help, neither of the workarounds is currently working. 

At the moment, the main project is still using vite and vite-plugin-windicss and is working. I will wait for the your bug fix to migrate the project to the latest version of sveltekit with the svelte-windicss-preprocess.

**Comment by alexanderniebuhr** [comment]
@moisesbites the workarounds should work, at least Workaround 1. Not sure why they do not work.

**Comment by alexanderniebuhr** [comment]
@moisesbites please try [v4.0.3](https://github.com/windicss/svelte-windicss-preprocess/releases/tag/v4.0.3) .. reopen with more information, if still breaking!

**Comment by moisesbites** [comment]
@alexanderniebuhr  Thank you very much! 

It's working now in `__layout.svelte`. 
```JS
//__layout.svelte
<style windi:preflights:global windi:safelist:global>
	:root {
		font-family: 'Lato', 'Open Sans', 'Segoe UI', 'Roboto';
	}

	:global(a) {
		@apply text-secundary hover:text-primary;
	}
</style>
```

```JSON
// package.json
{
  "name": "~TODO~",
  "version": "0.0.1",
  "scripts": {
    "dev": "svelte-kit dev",
    "build": "svelte-kit build",
    "preview": "svelte-kit preview",
    "lint": "prettier --check --plugin-search-dir=. . && eslint --ignore-path .gitignore .",
    "format": "prettier --write --plugin-search-dir=. ."
  },
  "devDependencies": {
    "@sveltejs/adapter-node": "^1.0.0-next.20",
    "@sveltejs/kit": "next",
    "eslint": "^7.26.0",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-svelte3": "^3.2.0",
    "prettier": "~2.3.0",
    "prettier-plugin-svelte": "^2.3.0",
    "svelte": "^3.38.2",
    "svelte-windicss-preprocess": "^4.0.3"
  },
  "type": "module"
}
```
