### ISSUE TITLE
Underline class family look not working.

### ISSUE THREAD

**Issue by LumaKernel** [windicss/svelte-windicss-preprocess#204]
### Describe the bug

Underline classes such as `underline-dotted`, `underline-double` simply look not working.

On https://windicss.github.io/svelte-windicss-preprocess/
![image](https://user-images.githubusercontent.com/29811106/125197537-22674900-e299-11eb-8996-4f44d70f4600.png)

https://windicss.org/play.html?html=DwEwlgbgfAUABHUk4GMA2BDAzlgvAIgFcA7EAUwCc0xiz9YEBIACTLTQHt5EB6cabsABGFODwZxB-VJhwES5KjTJwFlarQC0IDgBddZEPW4s2nQX0gTho8d0FYADhmIzseIqXXLjTVuy4EYB4nF2sRMQkHZ1d0d3kvJVpVRI0ybT0DIwlTAItQ4nDbKKCAQk1NOBcATwB3DGq4GggMahA4CusCtzlPRTSM-UNfOFzzIJCYosiYYP4oIA&css=Q
![image](https://user-images.githubusercontent.com/29811106/125197567-3612af80-e299-11eb-9235-2d77d7ac8456.png)

I also confirmed that is not working in local with latest version ( = 0.9.11).

### System Info

```shell
Need to install the following packages:
  envinfo
Ok to proceed? (y) y

  System:
    OS: Linux 4.19 Ubuntu 20.04.1 LTS (Focal Fossa)
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 1.77 GB / 15.55 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 14.15.4 - /tmp/fnm_multishells/19925_1625926601019/bin/node
    Yarn: 1.22.10 - /tmp/fnm_multishells/19925_1625926601019/bin/yarn
    npm: 7.6.3 - /tmp/fnm_multishells/19925_1625926601019/bin/npm
  IDEs:
    Nano: 4.8 - /usr/bin/nano
    VSCode: 1.43.2 - /mnt/c/Users/luma/scoop/shims/code
    Vim: 8.1 - /usr/bin/vim
  Browsers:
    Firefox: 84.0.2
  npmPackages:
    svelte: ^3.35.0 => 3.38.3
    windicss: ^2.5.3 => 2.5.14
```

### Used Package Manager

npm

**Comment by alexanderniebuhr** [comment]
https://windicss.github.io/svelte-windicss-preprocess/ uses Windicss v2, which did not include underline classes.
It won't be updated.

The new playground is https://windicss.org/play.html
I have changed the URL in the description. Do you have this issue on any project?

**Comment by LumaKernel** [comment]
Ah, sorry. I was perfectly misunderstanding. I'm using `vite-plugin-windicss`.
Thank you for your kind support. And updating `windicss` and `vite-plugin-windicss` resolved my issue.
