### ISSUE TITLE
HMR issue while reloading windi.config.ts changes

### ISSUE THREAD

**Issue by bhvngt** [windicss/svelte-windicss-preprocess#287]
### Describe the bug

My project uses `svelte+vite+cypress` to develop component library. I would like to hot reload changes done in `windi.config.js` during development. When I make extend color with following code inside `windi.config.js`, the changes are not reloaded. 

```
	theme: {
		extend: {
			colors: {
				primary: colors.yellow,
			},
```

Based on this [issue](https://github.com/windicss/vite-plugin-windicss/issues/139), if I change the extension to `ts`, it works. However, in doing so any color variations do not get reloaded when I change `color` in my svelte file from say `bg-yellow-100` to `bg-yellow-200`.  It throws following error in the console

```
Trying to load windi configuration from ./windi.config.ts
Unknown Error while loading the config
Error: typescript currently not supported
    at Object.load (./node_modules/.pnpm/svelte-windicss-preprocess@4.1.1/node_modules/svelte-windicss-preprocess/dist/index.js:98:11)
    at ./node_modules/.pnpm/svelte-windicss-preprocess@4.1.1/node_modules/svelte-windicss-preprocess/dist/index.js:332:28
    at new Promise (<anonymous>)
    at markup (./node_modules/.pnpm/svelte-windicss-preprocess@4.1.1/node_modules/svelte-windicss-preprocess/dist/index.js:324:14)
    at process_markup (file://./node_modules/.pnpm/svelte@3.44.0/node_modules/svelte/src/compiler/preprocess/index.ts:183:26)
    at preprocess (file://./node_modules/.pnpm/svelte@3.44.0/node_modules/svelte/src/compiler/preprocess/index.ts:224:30)
    at compileSvelte2 (file://./node_modules/.pnpm/@sveltejs+vite-plugin-svelte@1.0.0-next.30_svelte@3.44.0+vite@2.6.13/node_modules/@sveltejs/vite-plugin-svelte/src/utils/compile.ts:40:19)
    at TransformContext.transform (file://./node_modules/.pnpm/@sveltejs+vite-plugin-svelte@1.0.0-next.30_svelte@3.44.0+vite@2.6.13/node_modules/@sveltejs/vite-plugin-svelte/src/index.ts:172:24)
    at Object.transform (./node_modules/.pnpm/vite@2.6.13/node_modules/vite/src/node/server/pluginContainer.ts:509:20)
    at doTransform (./node_modules/.pnpm/vite@2.6.13/node_modules/vite/src/node/server/transformRequest.ts:160:27)
```

This seems to be happening because `@nbh/utils` used by the current library don't support typescript. If I make a force reload `vite.config.js` through any change then the color variations do get reloaded.

### System Info

```shell
System:
    OS: macOS 11.6
    CPU: (4) x64 Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz
    Memory: 88.69 MB / 16.00 GB
    Shell: 3.3.1 - /usr/local/bin/fish
  Binaries:
    Node: 16.12.0 - ~/Library/pnpm/node
    Yarn: 1.22.15 - /var/folders/n0/qyzlydqj6cv8qt68qd6dbprh0000gn/T/fnm_multishells/14429_1635420832550/bin/yarn
    npm: 8.1.0 - ~/Library/pnpm/npm
  IDEs:
    Nano: 2.0.6 - /usr/bin/nano
    VSCode: 1.61.2 - /usr/local/bin/code
    Vim: 8.2 - /usr/bin/vim
    Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
  Browsers:
    Chrome: 95.0.4638.54
    Chrome Canary: 97.0.4685.0
    Edge: 95.0.1020.40
    Firefox: 93.0
    Safari: 15.0
  npmPackages:
    svelte: ^3.44.0 => 3.44.0
    svelte-windicss-preprocess: ^4.1.1 => 4.1.1
    windicss: ^3.2.0 => 3.2.0
```

### Used Package Manager

pnpm

**Comment by alexanderniebuhr** [comment]
@bhvngt thanks for the idea of supporting live reload for config files. This feature is currently not implemented, I will address this as soon as possible

**Comment by alexanderniebuhr** [comment]
Just added first iteration [(v4.1.5-beta.1)](https://www.npmjs.com/package/svelte-windicss-preprocess/v/4.1.5-beta.1) with experimental support. Have not released it on stable yet.  If you would like to test, and see if it works with vite - I am not testing with vite currently -  please use:

```sh
npm i svelte-windicss-preprocess@4.1.5-beta.1
```

**Comment by bhvngt** [comment]
Sure @alexanderniebuhr. I will do the testing from my end with vite.

**Comment by bhvngt** [comment]
I have setup a [sandbox](https://codesandbox.io/s/boring-greider-ny1kv?file=/index.html) to test out your build. I did my testing with following results

1. Setup custom colors  in `windi.config.ts`
![image](https://user-images.githubusercontent.com/79074469/139638246-b1850936-f5dd-4ccb-8327-ff059b791faf.png)
2. Using this colors in `app.svelte'
![image](https://user-images.githubusercontent.com/79074469/139638308-34378799-81bd-4607-8d8d-04594bd8b9b5.png)
![image](https://user-images.githubusercontent.com/79074469/139638162-52b8cdfd-f9c6-46bd-be6f-a85bf4c8bd29.png)
3. When I make changes in `windi.config.ts`, it live reloads this changes.
![image](https://user-images.githubusercontent.com/79074469/139638393-ca46a22a-5182-43b7-a881-a0caa7a577d8.png)
4. When I make changes in `app.svelte`, changes don't get reflected. This time however, no error is thrown
![image](https://user-images.githubusercontent.com/79074469/139638478-3692e9d5-1064-4929-bf18-ae9db2ddebaa.png)
5. When I touch `vite.config.js`, `vite` restarts the server and so the changes gets reloaded.
![image](https://user-images.githubusercontent.com/79074469/139638594-53f1a606-2dff-4f60-a41b-91a5f78a7c7f.png)

**Comment by alexanderniebuhr** [comment]
Hm that is strange and I don't think it is an issue with the reload of the config, since it already picked up the config.

I will check your repo later, I am afraid it is caused by some lifecycle issue of svelte and vite. 

I'll update as soon as I know the reason

**Comment by bhvngt** [comment]
You are right. I had to put`WindiCss` before `svelte` in the `plugin` section of `vite.config.js`. This answer in `[stackoverflow](https://stackoverflow.com/questions/69601626/windi-css-hmr-not-working-for-svelte-vite-app)` helped me fix this issue.

With this change, it all seems to be working out fine. Thanks a ton for your super quick patch.

**Comment by bhvngt** [comment]
I tried the same fix in my current setup with `svelte-windicss-preprocess@4.1.1` and that seems to have resolved the reloading issue with `typescript` based config file. 

I still see `Error: typescript currently not supported` error when I test it with your `4.1.5-beta.1` build. Not sure if I should ignore that!!

**Comment by alexanderniebuhr** [comment]
Typescript config files are currently not really supported (had to disable support for them some versions ago). I would suggest `.mjs` for best support. Adding `.ts` support later, but if it works, you can ignore the message.

**Comment by alexanderniebuhr** [comment]
With the beta release you should be able to use `.js` and if the file does trigger vite, just change a svelte file after changing the config and it should load the new config automatically :)

**Comment by bhvngt** [comment]
Thats true. Works the way you have explained. Thanks a ton...
