### ISSUE TITLE
plugin styles breaking if in main svelte file

### ISSUE THREAD

**Issue by alexanderniebuhr** [windicss/svelte-windicss-preprocess#32]
combined in one issue for better tracking.

styles are getting sorted in wrong order (happens not all the time) therefore breaking if not in component file. This happens for typography and forms so far. Need to do more debugging.

**Comment by alexanderniebuhr** [comment]
will debug this tomorrow

**Comment by alexanderniebuhr** [comment]
@prab-it @munxar I am not happy with that, but I would like to ask you guys test your cases with the new examples for rollup & snowpack. (I will add `svelteKit` later, however we might not support that fully until it is released) I think that the old examples where outdated, and this might have led to some issues. I am more than happy to fix this, however first we need to find out if this is happening caused by outdated example configuration or if this is still happening with the new examples. In parallel, I will be making more debugging on my side too. 
Thanks, you, guys!

https://github.com/windicss/svelte-windicss-preprocess/tree/main/example/rollup
https://github.com/windicss/svelte-windicss-preprocess/tree/main/example/snowpack

**Comment by prab-it** [comment]
@alexanderniebuhr ok, I tested on both, `Sapper` and `SvelteKit`.

`Sapper + Rollup:`
The `bundle.css` made with `rollup-plugin-css-only` fix the issue.

`SvelteKit + Snowpack:`
Works partially with `npm run dev` and it doesn't work with `npm run build && npm run start`.

**Comment by alexanderniebuhr** [comment]
you used the outdated examples?

**Comment by prab-it** [comment]
@alexanderniebuhr I used the latest examples.
https://github.com/windicss/svelte-windicss-preprocess/tree/main/example/rollup
https://github.com/windicss/svelte-windicss-preprocess/tree/main/example/snowpack

**Comment by alexanderniebuhr** [comment]
and you added `Sapper` and `svelteKit` yourself?

**Comment by prab-it** [comment]
@alexanderniebuhr yes.

**Comment by alexanderniebuhr** [comment]
ok. I am working on examples for `Sapper` and `svelteKit`, just need some more time. Please wait until I finish them, and then look if the setup is close to yours & what is different. I really need to find out if this issue is setup or bundler specific, because I do not see any issue in CSS parsing right now. So it has to be a combination of two!

**Comment by prab-it** [comment]
@alexanderniebuhr ok, thanks BTW!
Try my `sveltekit-windicss` repo with bug:
[sveltekit-windicss.zip](https://github.com/windicss/svelte-windicss-preprocess/files/6043255/sveltekit-windicss.zip)

**Comment by alexanderniebuhr** [comment]
@prab-it `globalUtility: false` works for me in your project, as I concluded earlier this might also be the correct way to set with bundlers splitting files into multiple css

**Comment by prab-it** [comment]
@alexanderniebuhr you are right, `globalUtility: false` fix the issue! 👍 
I don't know what was the problem last time with `globalUtility: false`, but it works!
Is it possible achieve something like this with `Sapper + Rollup`, I mean without `rollup-plugin-css-only`?
Thanks again for your support!

**Comment by alexanderniebuhr** [comment]
Do not have any Rollup Setup right now, can you share yours too. Then I can have a look

**Comment by prab-it** [comment]
@alexanderniebuhr wait a second, I found what was the problem, if I set `globalUtility: false`, now I can't pass `class` as `prop` to my `Input` component.
ex. try to set `border-8`, it doesn't work...

`src/routes/index.svelte:`
```svelte
<script>
  import Input from '$components/Input.svelte';
</script>

<form action="#">
  <Input type="text" placeholder="input 1" class="border-8" />
</form>
```

**Comment by prab-it** [comment]
@alexanderniebuhr this is my `sapper-ts-windicss` repo: 
[sapper-ts-windicss.zip](https://github.com/windicss/svelte-windicss-preprocess/files/6043941/sapper-ts-windicss.zip)

**Comment by alexanderniebuhr** [comment]
> if I set `globalUtility: false`, now I can't pass `class` as `prop` to my `Input` component.

Ok this is what I told you on the closed issue, then there are only two ways of fixing it, I think.

a) make `svelteKit` bundling in one splitted css and not multiple css.
b) make a safelist option, where you define the classes, you need.

Otherwise, you could have a look at different plugins for windicss which are parsing post compile and not precompile.

**Comment by alexanderniebuhr** [comment]
@prab-it will be fixed soon. subscribe https://github.com/windicss/svelte-windicss-preprocess/issues/35

**Comment by munxar** [comment]
@alexanderniebuhr the rollup example in main branch works for me, no issues so far.

**Comment by prab-it** [comment]
@alexanderniebuhr found an issue with `rollup` with `bundle` option, for more info download attached `rollup-windicss.zip` and open `App.svelte`.
[rollup-windicss.zip](https://github.com/windicss/svelte-windicss-preprocess/files/6048704/rollup-windicss.zip)

**Comment by alexanderniebuhr** [comment]
will check later

**Comment by prab-it** [comment]
@alexanderniebuhr ok the main issue is related to live changes. Restart the `dev` server fix this issue.
How to reproduce the issue:
1 - `$ npm run i`
2 - `$ npm run dev`
3 - add one more `Input` in `src/App.svelte`
```svelte
<Input type="number"></Input>
```
`Preview:`
![rollup-windicss-bundle-issue-preview](https://user-images.githubusercontent.com/68732594/109286911-2e3efb00-7823-11eb-817c-14ce44de03d3.png)

**Comment by alexanderniebuhr** [comment]
Again `globalUtility: false` is the solution and then https://svelte.dev/repl/88c699452f7644afa71f101a5a1b06d2?version=3.24.0 if you need to parse classes as props. Your use case is not support by svelte. Svelte is all about scoped styles. So, the styles need to be defined in the component or in a style tag with (both needs unreleased svelte-windicss-preprocessor and svelte-preprocessor)

```svelte
<style global>
   ...
</style>
```
```svelte
<style>
   :global(h1) {
     ...
  }
</style>
```

**Comment by alexanderniebuhr** [comment]
actually it works for me, even with `globalUtility: true`, cannot reproduce ur issue
