### ISSUE TITLE
CSS not included if filename is other than index.svelte in subfolders

### ISSUE THREAD

**Issue by wiesson** [windicss/svelte-windicss-preprocess#33]
The examples have just been refactored, but if I just started to use them 😅 . 

If I click on a blog post in the sapper rollup example:

https://github.com/windicss/svelte-windicss-preprocess/tree/main/example/outdated/sapper-webpack/src/routes/blog

The styles are not loaded:

```
GET http://localhost:3000/blog/client/client-d93a1e23.css net::ERR_ABORTED 404 (Not Found)
GET http://localhost:3000/blog/client/[slug]-72d51346.css net::ERR_ABORTED 404 (Not Found)
GET http://localhost:3000/blog/client/client-d93a1e23.css net::ERR_ABORTED 404 (Not Found)
GET http://localhost:3000/blog/client/[slug]-72d51346.css net::ERR_ABORTED 404 (Not Found)
```

I suspect, that the import path is relative, not absolute and while adding `/blog to the path, it breaks.

**Comment by alexanderniebuhr** [comment]
@wiesson can u test latest commit on main

https://github.com/windicss/svelte-windicss-preprocess/commit/c5bc1ed6aae8947609704756cf574a7e9144f8c1

**Comment by wiesson** [comment]
Thanks! 

I think I have an error somewhere. (Serviceworker / Caching - Not sure), because now it suddenly works. 🤷

**Comment by alexanderniebuhr** [comment]
@wiesson I changed some paths. So might be my issue. I am closing here. If you encounter anything, let me know!
