### ISSUE TITLE
Example for tailwind directives

### ISSUE THREAD

**Issue by wiesson** [windicss/svelte-windicss-preprocess#34]
I have added

```
<style>
  :root {
   ...
   // some default css vars
  }

  .form-input,
  .form-select {
    @apply block w-full border border-gray-300 rounded-md shadow-sm py-2 px-3 focus:outline-none focus:ring-gray-900 focus:border-gray-900 sm:text-sm;
  }
</style>
```

to a `_layout.svelte` file and somehow the classes are not taken into account. Any idea why? Could you update the sapper example as well? 🤗 

I also tried `<style global>...</style>`

**Comment by alexanderniebuhr** [comment]
check your terminal logs. Rollup shows you why it has not taken them into account. Seems that it removes unused styles. You also see that windicss is parsing the classes. So, check if you can change the rollup config.

Also, I am not sure what to do with `Sapper` and `SvelteKit`, one is going to be replaced the other one needs some more time to be production ready, so I do not feel safe to suggest any example for that.

**Comment by wiesson** [comment]
Yes, I'd like to switch to SvelteKit ASAP (from Sapper) but it's just not ready and has major breaking changes on a nightly bases. So we have to hold our Sapper App as long as possible. 

You are right, windicss does parse the classes 

```
src/components/Globalstyle.svelte
Unused CSS selector ".form-select:focus"
37: }
38: .form-input,
39:   .form-select:focus {
      ^
40:   outline: 2px solid transparent;
41:   outline-offset: 2px;
```

but rollup somehow removes them? Any idea, where I could look?

**Comment by alexanderniebuhr** [comment]
rollup.config.js and used svelte plugin (rollup-plugin-svelte) for rollup. Svelte removes unused styles, I guess. But somehow you can change, might found config for rollup-plugin-svelte

**Comment by wiesson** [comment]
I was able to wrap the global styles with `:global()` and it looks like, its working as expected!

**Comment by alexanderniebuhr** [comment]
It should wrap global styles with :global()
I might have an idea where to fix. Let me check later today

**Comment by alexanderniebuhr** [comment]
@wiesson can u test with latest master and latest rollup example. Should include global styles if using

```svelte
<style global>

</style>
```

**Comment by wiesson** [comment]
Hmm, it did not work for me. I have created an example repo -> https://github.com/wiesson/svelte-sapper-windicss/blob/main/src/components/Styles.svelte (but still wrapped with :global())

**Comment by alexanderniebuhr** [comment]
@wiesson the change is not released as a package yet. However, you gut try it with this repo and the examples here. Next release is scheduled later tonight.
