### ISSUE TITLE
use pnpm as dev dependency

### ISSUE THREAD

**Issue by munxar** [windicss/svelte-windicss-preprocess#37]
# steps to reproduce
- git clone repo
- npm i
- npm run build // or other npm tasks
will give an error if the person does not have pnpm installed locally.
adding pnpm as dev dependency would fix.

this is not urgent I personally just don't use pnpm and I like if repos are self contained if i do npm i && npm whatever.

A note in the README that pnpm is a dev dependency would work too.

just close this issue if you think otherwise.

**Comment by alexanderniebuhr** [comment]
@munxar We will stay with pnpm for the time being, but for scripts would this work?? 

```
"build": "rollup -c && npx pnpm tsd"`
```

**Comment by munxar** [comment]
yes that works, but in favor of simplicity just add it to devDependencies.
you can keep your scripts as is, and someone without pnpm installed would have the same in the end as running npx all the time.

**Comment by alexanderniebuhr** [comment]
make pr please
