### ISSUE TITLE
Breaks .svelte modules

### ISSUE THREAD

**Issue by jakobrosenberg** [windicss/svelte-windicss-preprocess#43]
I have a svelte module:

```html
<script context="module">
  ...
  export { something }
</script>

<script>
  ...
</script>

<h1>hello<h1>
```

Whenever I add `svelte-windicss-preprocess`, I can no longer import the module. Instead the bundler hangs. Have tried Rollup and Snowpack.

**Comment by alexanderniebuhr** [comment]
will be fixed with next release

**Comment by alexanderniebuhr** [comment]
@jakobrosenberg do you know if rollup and snowpack hangs, or if windicss-preprocess hangs??

**Comment by jakobrosenberg** [comment]
I'm not able to tell.  I just know they hang indefinitely without logging any errors.

**Comment by alexanderniebuhr** [comment]
can you share your project somehow? I can't reproduce currently with the examples in this repo

**Comment by jakobrosenberg** [comment]
I'll see if I can create a reproducible.

I've narrowed it down to this loop which seems to run indefinitely.

https://github.com/windicss/svelte-windicss-preprocess/blob/a78fc15114a8200211782e66cc66ceb1486208ba/src/utils.ts#L15-L26

**Comment by jakobrosenberg** [comment]
It loops back and forth between these two:

![image](https://user-images.githubusercontent.com/4153004/110024178-59977d80-7d2e-11eb-87b5-389dfec1ff81.png)

![image](https://user-images.githubusercontent.com/4153004/110024193-6025f500-7d2e-11eb-957e-a54253651af5.png)

**Comment by alexanderniebuhr** [comment]
I have an idea.. might be issue because `@apply` is style, and ur text is `apply` with some other logic. So there might be a matching error. I have to debug this more. If you can, please show the part with `apply: (url) =>`

**Comment by jakobrosenberg** [comment]
Here's the component

<details>

```html
<script context="module">
  import { writable, get } from "svelte/store";
  import { page } from "@roxi/routify";

  const languages = {
    en: { short: "en", long: "english", default: true },
    fr: { short: "fr", long: "french" },
    de: { short: "de", long: "german" },
  };

  // let's use a store for reactivity
  const language = writable(languages["en"]);

  const urlTransform = {
    apply: (url) => {
      /**
       * external URL
       * if the selected language is not the default language,
       * we want to use the language as an URL prefix
       */
      const lang = get(language);
      const prefix = !lang.default ? `/${lang.short}` : "";
      return prefix + url;
    },
    remove: (url) => {
      /**
       * internal URL
       * if the first url fragment matches a language,
       * we're gonna strip the fragment
       */
      const [, urlPrefix, ...rest] = url.split("/");
      if (languages[urlPrefix]) {
        language.set(languages[urlPrefix]);
        return [, ...rest].join("/");
      } else return url;
    },
  };

  export { languages, language, urlTransform };
</script>

<script>
  import { goto, url } from "@roxi/routify";
  const handleChange = () => {
    $goto($page.path);
  };
</script>

<select bind:value={$language} on:change={handleChange}>
  {#each Object.values(languages) as lang}
    <option value={lang}>{lang.long}</option>
  {/each}
</select>
```

</details>

**Comment by alexanderniebuhr** [comment]
thanks that help me.
Will Update the parser right now :)

**Comment by alexanderniebuhr** [comment]
please try pre-Release of experimental parser https://github.com/windicss/svelte-windicss-preprocess/releases/tag/v3.0.0-beta.1

**Comment by trevyn** [comment]
I was also running into a hang with 2.3.1, and 3.0.0-beta.1 resolves it.

**Comment by jakobrosenberg** [comment]
I'm getting a bunch of warnings for Svelte's `export let` as well as this error:
```
[!] (plugin svelte) ParseError: Unexpected token
node_modules\@roxi\routify\runtime\Router.svelte
17:   export let config = {}
18:   let nodes
19:   let navigator window.routify = window.routify || {}
                    ^
```

This is the actual code on line 12-15:
```javascript
  let nodes
  let navigator

  window.routify = window.routify || {}
  ```

**Comment by alexanderniebuhr** [comment]
yes, working in that. Lead by missing semicolons, is a bug

**Comment by jakobrosenberg** [comment]
That fixed it. Here's the next one 😎
```
[!] (plugin svelte) ParseError: Expected }
src\pages\index.svelte
14:   {#each nodes as node, index}
15:     {#await node.componentWithIndex then [Cmp, Index]}
16:       <div class="page even:{index even:% even:2} " class:un id="{node.title}">
                                       ^
17:         <div class="container">
18:           <svelte:component this="{Cmp}">
```

The actual code
```html
{#each nodes as node, index}
  <!-- componentWithIndex also returns an `index.svelte` file if one exists -->
    {#await node.componentWithIndex then [Cmp, Index]}
      <div class="page" class:uneven={index % 2} id={node.title}>
```

**Comment by alexanderniebuhr** [comment]
this is a hard one. However, I think with latest beta https://github.com/windicss/svelte-windicss-preprocess/releases/tag/v3.0.0-beta.7 should work. You have a good project with many cases to test. So please submit any issue.

Parser v3 should be stable soon...

**Comment by jakobrosenberg** [comment]
Seems this is finally working. Thanks for all your work @alexanderniebuhr! 👍

**Comment by alexanderniebuhr** [comment]
If you find any issue please let me know.
