### ISSUE TITLE
Extra space concatenated between text and expression

### ISSUE THREAD

**Issue by grenierdev** [windicss/svelte-windicss-preprocess#44]
I'm using template literal in my class attribute ```class={`resizer resizer--${axe}`}```. It get preprocessed as ```class="resizer resizer-- {axe}"``` (notice the space between `--` and `{axe}`).

I've dug into the code and found out these two lines. They introduce an extra space between the text and expression part of the attribute.

https://github.com/windicss/svelte-windicss-preprocess/blob/12c4040476569b839e60350bb5ab29d9e751127c/src/index.ts#L135
https://github.com/windicss/svelte-windicss-preprocess/blob/12c4040476569b839e60350bb5ab29d9e751127c/src/index.ts#L141

Am I missing something, a limitation of the preprocessor with template literal perhaps?

I'd be happy to create a PR to remove the space there.

**Comment by alexanderniebuhr** [comment]
pr are welcome, you are looking wrong. windicss expressions != template literals look here

https://github.com/windicss/svelte-windicss-preprocess/blob/12c4040476569b839e60350bb5ab29d9e751127c/src/utils.ts#L82

**Comment by alexanderniebuhr** [comment]
but you might not be able to use the styles like you do i am afraid, but try

**Comment by grenierdev** [comment]
@alexanderniebuhr Thanks for the pointer.

If we take the same example described in the `convertTemplateSyntax`

https://github.com/windicss/svelte-windicss-preprocess/blob/12c4040476569b839e60350bb5ab29d9e751127c/src/utils.ts#L83-L85

That function actually generates 2 spaces after `green`.
```
<div class="green  {myClass ? 'red' : 'green'}">Should be red!</div>
                  ^ extra space introduced by replacing the dollar sign with a space
```

I'm still new to the svelte syntax, but wouldn't it be better to `.replace(/$\{/g, '{')` ?

**Comment by alexanderniebuhr** [comment]
pls try and submit pr, i will review

**Comment by grenierdev** [comment]
Settled with ```class="resizer {'resizer--'+axe}"```
