### ISSUE TITLE
`export let active = false` is preprocessed

### ISSUE THREAD

**Issue by tmaxmax** [windicss/svelte-windicss-preprocess#46]
I discovered that if you have the following Svelte code

```svelte
<script>
  export let active = false
</script>
```

the Javascript code ends like this:
```js
export let class="active:false"
```

If I remove the windicss preprocess from the config, this doesn't happen anymore. What is happening here?

**Comment by alexanderniebuhr** [comment]
I update the parser right now. New version should be available soon

**Comment by alexanderniebuhr** [comment]
please try pre-Release of experimental parser https://github.com/windicss/svelte-windicss-preprocess/releases/tag/v3.0.0-beta.1

**Comment by tmaxmax** [comment]
It seems to work now

**Comment by alexanderniebuhr** [comment]
Ok I need to improve a bit more with the new parser, but should be released soon. Please be a little patient! You can always use beta release, I will try to keep it as stable as possible

**Comment by alexanderniebuhr** [comment]
closing since it should work if you experience any bugs. please open new issues
