### ISSUE TITLE
Import Base, Components, Utilities?

### ISSUE THREAD

**Issue by nivoc** [windicss/svelte-windicss-preprocess#51]
Usually in Tailwind you have to import 
@tailwind base;
@tailwind components;
@tailwind utilities;

somewhere. Is it required with svelte-windicss-preprocess? Or does svelte-windicss-preprocess always include the three?

**Comment by noahsalvi** [comment]
No it isn't required
https://windicss.netlify.app/guide/migration.html#base-styles

**Comment by nivoc** [comment]
Thanks for the link!
