### ISSUE TITLE
Extra classes with {$$props.class}

### ISSUE THREAD

**Issue by wiesson** [windicss/svelte-windicss-preprocess#54]
Windi fails with

```
// SomeComponent.svelte
<div class="p-4 {$$props.class}">Hello</div>
```

Usage
```
<SomeComponent class="bg-blue" />
```

Any idea, how to add this feature? :)

**Comment by alexanderniebuhr** [comment]
Might not be added at all. You are trying to use dynamic classes. See the issue "dynamic classes" for that. This is an preprocessor running before svelte runs. So anything svelte handles such as props is not supported. You might be able to use the solution of @munxar

**Comment by wiesson** [comment]
ah ok! Makes sense to me. FYI - I kind of solved by using:

```
// SomeComponent.svelte
<script>
let className = "";
export { className as class };
</script>

<div class="p-4 {className}">Hello</div>
```

**Comment by alexanderniebuhr** [comment]
I wonder that this is working, shouldn't work. Are u using v2 or v3?

**Comment by lamualfa** [comment]
> I wonder that this is working, shouldn't work. Are u using v2 or v3?

Worked in v2 & v3. I have been tested.
