### ISSUE TITLE
What's the idiomatic way to apply dynamic classes in Svelte?

### ISSUE THREAD

**Issue by awmcclain** [windicss/svelte-windicss-preprocess#56]
I'm trying to migrate over to windi but I'm running into issues with compiling some of the tailwind workarounds we needed to implement in Svelte.

What we're trying to express is this: set the color to `bg-red-600` if the `foo` variable is true, otherwise set it to a dynamic color. Here's how we worked things before:

```  
<div class="{foo ? 'bg-red-600' : `bg-${colorLookup(index)}-600`}">
```

where `colorLookup()` returns strings like `"purple"` or `"green"`.

Is there a way to both dynamically apply a color class depending on another dynamic variable? It's fine if we need to list out every class that the `colorLookup()` function would generate (i.e. `bg-purple-600` `bg-green-600` etc).

**Comment by alexanderniebuhr** [comment]
I can add this to v3. 👍

**Comment by alexanderniebuhr** [comment]
@awmcclain also reference the ideas here https://github.com/windicss/svelte-windicss-preprocess/issues/35#issuecomment-790940288. Might also be an option for you

**Comment by alexanderniebuhr** [comment]
will be fixed in beta.9 later today

**Comment by alexanderniebuhr** [comment]
@awmcclain https://github.com/windicss/svelte-windicss-preprocess/releases/tag/v3.0.0-beta.9
