### ISSUE TITLE
Dynamic class doesn't render

### ISSUE THREAD

**Issue by sdelon** [windicss/svelte-windicss-preprocess#64]
Using Windi with sapper, I have an issue when passing a tailwind class as a prop. I am building a responsive nav which has a "direction" prop such as flex-row on large device and flex-col on smaller ones : 

`<ul class="flex {direction} justify-end space-x-8">`

But this direction prop doesn't render on smaller device. I looked in the developer tools and when I uncheck the windi class (eg: windi-15d8t28) that is created, it works fine.

Thanks!

**Comment by alexanderniebuhr** [comment]
https://github.com/windicss/svelte-windicss-preprocess/issues/35

**Comment by alexanderniebuhr** [comment]
actually one solution is https://github.com/windicss/svelte-windicss-preprocess/releases/tag/v3.0.0-beta.9

**Comment by alexanderniebuhr** [comment]
should work with safelist and automatic class parsing in https://github.com/windicss/svelte-windicss-preprocess/releases/tag/v3.0.0-beta.12
