### ISSUE TITLE
add support for SvelteKit

### ISSUE THREAD

**Issue by alexanderniebuhr** [windicss/svelte-windicss-preprocess#65]
https://github.com/sveltejs/kit

**Comment by benmccann** [comment]
I see SvelteKit mentioned on the readme, but one thing to note - `snowpack.config.cjs` has been replaced with `vite.config.js`: https://github.com/sveltejs/kit/blob/master/packages/create-svelte/template/vite.config.js

**Comment by SamLewis0602** [comment]
Pumped for this, hoping the integration between windicss and svelte can be simplified with the switch to Vite for SvelteKit. Happy to be a guinea pig to help test any changes.

**Comment by dominikg** [comment]
note there is also  https://github.com/windicss/vite-plugin-windicss/issues/54 for svelte + windicss + vite to work best, the two vite plugins need to cooperate

**Comment by alexanderniebuhr** [comment]
if you guys have any suggestion for the readme. please submit pr

**Comment by zackartz** [comment]
Last night when I tried this out it was working fine (with vite) but now I get this error.
```
ReferenceError: Layout is not defined
    at root.svelte:6:12
    at $$render (/home/zack/dev/poggers/node_modules/svelte/internal/index.js:1369:22)
    at Object.render (/home/zack/dev/poggers/node_modules/svelte/internal/index.js:1377:26)
    at get_response (file:///home/zack/dev/poggers/node_modules/@sveltejs/kit/dist/ssr.js:2289:27)
    at async get_response (file:///home/zack/dev/poggers/node_modules/@sveltejs/kit/dist/ssr.js:2293:10)
    at async render_page (file:///home/zack/dev/poggers/node_modules/@sveltejs/kit/dist/ssr.js:2403:9)
    at async ssr (file:///home/zack/dev/poggers/node_modules/@sveltejs/kit/dist/ssr.js:2541:20)
    at async Immediate.<anonymous> (file:///home/zack/dev/poggers/node_modules/@sveltejs/kit/dist/chunks/index.js:3273:23)
```

when starting a new project.

Is this a problem with windicss or is this a sveltekit problem?

**Comment by alexanderniebuhr** [comment]
need more information about the project to tell you.. can't see any useful information in the stack trace

**Comment by zackartz** [comment]
Using the latest version of the package and the problem just disappeared. All good now, thanks.

**Comment by NoelJacob** [comment]
Do I use this or [windicss/vite-plugin](https://github.com/windicss/vite-plugin-windicss) for better speed?

**Comment by alexanderniebuhr** [comment]
@NoelJacob schould not be any difference in speed. just difference in the position. I suggest you try vite-plugin first. if you have a special use case or feel pre-processing might be better, you would com back to this repo

**Comment by alexanderniebuhr** [comment]
suggest to use [windicss/vite-plugin](https://github.com/windicss/vite-plugin-windicss)

**Comment by Evertt** [comment]
For anyone checking this thread, these guys got it to work:

https://github.com/svelte-add/windicss

**Comment by alexanderniebuhr** [comment]
@Evertt thanks for the info.. also the problem for us currently is not the support installing it, it is more getting it to work correctly with SSR+SPA. 

We appreciate any solution which does works with preprocessor in SSR

**Comment by Evertt** [comment]
@alexanderniebuhr I believe their solution works for SSR? At least I haven't noticed any issues? Would I need to do something specific to test whether windicss works with SSR specifically?

**Comment by alexanderniebuhr** [comment]
Look at some issues in this repo, for most people it works fine. But we have some more edge cases with hybrid which has client and serve +

- Note to look for would be global utility and Preflights
- Compile vs non compile 
- Scoped styles

But you can check both windicss integration and choose the one best for your project.. if preprocessor works it's great. We currently just do not focus on fixing svelte kit specific issues, since there is always the vite plugin as an alternative -> seems currently to work better with SSR ..

**Comment by Evertt** [comment]
Ah okay, thanks for clarifying.

>

**Comment by alexanderniebuhr** [comment]
@Evertt update to [v3.2.0](https://github.com/windicss/svelte-windicss-preprocess/releases/tag/v3.2.0)
add to your windicss config, should work in all modes.. note you will not get de-duplication, other than svelte native
```js
    {
      kit: true, // ADD
      config: 'windi.config.cjs',
    }
```

**Comment by Evertt** [comment]
@alexanderniebuhr I just looked at the issue about preflight missing in Sapper's production build and now I noticed that I have the same issue when using this plugin for svelte-kit I actually have the same issue. Are you already aware of that?

> note you will not get de-duplication, other than svelte native

In which cases could I still get duplicate code then?

**Comment by alexanderniebuhr** [comment]
do `mode: dev` as config for the preflight issue pls :)

Duplicate code would be preflights and classes used in multiple file (if not using compile mode). But that is the expected behavior for scoped styles.

**Comment by Evertt** [comment]
Oh, having duplicated preflights does sound like potentially a lot of duplication. 😅 
Okay I might switch over to the vite plugin then. I've noticed though, that when using the vite-plugin, I no longer can do things like:

```html
<style>
  .button {
    @apply sm:p-2;
  }
</style>
```

Because then svelte(-kit) will then complain at the `:` character during the build process. Is that fixable?

**Comment by alexanderniebuhr** [comment]
we are working on fixing preflights, not finished yet

**Comment by dominikg** [comment]
i'm sorry it's taking so long for a new vite-plugin-svelte release. It should get a lot easier with that. 
In the mean time, @bluwy has a workaround how to add the cooperating windicss preprocessor manually: https://github.com/bluwy/pick-palette/blob/a4c37dfe3d7cdd150d87b78842839e75e2830cf7/vite.config.ts#L11

**Comment by alexanderniebuhr** [comment]
@dominikg can you give me some insight what will change with new release.. will it handle files in svelte logic. or still parallel, and calling new preprocessor for each file? please hit me up, either here or discord!

**Comment by dominikg** [comment]
code is here https://github.com/sveltejs/vite-plugin-svelte/pull/13 basically vite-plugin-windicss and vite-plugin-svelte cooperate with each other. vite-plugin-windicss exposes a svelte preprocessor that vite-plugin-svelte adds automatically. So adding both plugins should work for the user without the need to add another svelte preprocessor themselves. 

This should also take care of duplicated global styles.

**Comment by alexanderniebuhr** [comment]
@dominikg yeah found that out later today. this is great and good for all people. still going to suggest that. but there might people want to use this repo, since they want to process everything before svelte pipeline. We will see and adapt to the new release :)

**Comment by dominikg** [comment]
yes, that solution obviously only works inside vite. so the separate svelte-windicss-preprocess is still needed for other cases

**Comment by alexanderniebuhr** [comment]
even know people wanting to preprocess with vite.. still not thinking it is the correct way, but people have very specific projects
