### ISSUE TITLE
:global() in styles makes everything :global()

### ISSUE THREAD

**Issue by filipot** [windicss/svelte-windicss-preprocess#67]
Just started using this, so dunno if this is intended or not. Btw love it!

This
`<style>
    :global(p){
    }
	.something{
		font-size: 1.4em;
	}
</style>
`

Becomes this:
`<style>
    :global(p){
    }
	:global(.something){
		font-size: 1.4em;
	}
</style>
`

if there is one or more :global() in the style the :global() gets added to all elements in the style tag

Using the default svelte configuration in the readme

**Comment by alexanderniebuhr** [comment]
should be fixed with https://github.com/windicss/svelte-windicss-preprocess/releases/tag/v3.0.0-beta.11
