### ISSUE TITLE
Change "Configuration" in README.md

### ISSUE THREAD

**Issue by bbtgnn** [windicss/svelte-windicss-preprocess#72]
Hi! This is the first time I give a suggestion on GitHub, so please forgive me anything incorrect I do :)

In README.md, under the "Configuration" section, the first line of code looks like this:
`// svelte.config.js`

I think it should be:
`// windi.config.js`

Cause if I create a `svelte.config.js` file I get an error for a missing `windi.config.js`.

Hope I've been useful, and, again, sorry for eventually sounding unpolite (not really expert in english) or posting in the wrong place / by not following any procedures 🙌

**Comment by alexanderniebuhr** [comment]
hey there,
thanks for your time and your comment. :) 
Everything is fine, you are very polite and you should always keep up your pace to post stuff on GitHub.

You are totally right, the README.md is not very complete.
You need a `svelte.config.js` and a `windi.config.js` > the svelte config is to include the preprocessor, and the windi config is to change windi css config. :)
