### ISSUE TITLE
Do not parse variant attribute on slot

### ISSUE THREAD

**Issue by www-chique** [windicss/svelte-windicss-preprocess#79]
I noticed that the "active", "hover", etc. variant attributes are being parsed on slots as well.
Not sure if it is intended.
Slots are not real elements and shouldn't have any class or styling applied on them anyways.
So maybe we can skip parsing variant attributes if the tag is "slot"?

**Example:**
(Component.svelte)
`<slot active={someCondition}/>`

Here I am using the "active" as a property value, so that when passing "things" into the slot, I can use that variable. For example:
```
<Component let:active>
    <div class:text-red-500={active}>
     Something
    </div>
</Component>
```

**Comment by alexanderniebuhr** [comment]
@www-chique do you know for what variant attributes this would be actually needed?

**Comment by www-chique** [comment]
> 
> 
> @www-chique do you know for what variant attributes this would be actually needed?

I think you have a list against which you try to apply those variants. And I believe it's just "hover", "focus" and "active",
Do you have any other variant that can be applied as an _"attribute"_ in **svelte-windicss-preprocess**?
The best fix would be to ignore the entire logic if the element is a `<slot>`.

Maybe I did not explain it good, so instead of knowing what variants to exclude or include, I am suggesting to skip the entire logic of variants as attribute feature if the target tag is "slot".

**Comment by alexanderniebuhr** [comment]
ok got you

**Comment by alexanderniebuhr** [comment]
closing in favor of [v3.1.4](https://github.com/windicss/svelte-windicss-preprocess/releases/tag/v3.1.4)
