### ISSUE TITLE
Breakpoints not working

### ISSUE THREAD

**Issue by pikeas** [windicss/svelte-windicss-preprocess#83]
```
//svelte.config.cjs
const sveltePreprocess = require("svelte-preprocess")
const sveltewindiCSSPreprocess = require("svelte-windicss-preprocess")
const node = require("@sveltejs/adapter-node")
const pkg = require("./package.json")

/** @type {import('@sveltejs/kit').Config} */
module.exports = {
    preprocess: [
        sveltePreprocess({
            defaults: {
                script: "ts",
            },
        }),
        sveltewindiCSSPreprocess.preprocess(),
    ],
    kit: {
        adapter: node(),
        target: "#svelte",
        vite: {
            ssr: {
                noExternal: Object.keys(pkg.dependencies || {}),
            },
        },
    },
}
```

```
// any component
<p>Before</p>
<div class="hidden md:block lg:hidden">Only medium</div>
<div class="hidden lg:block">Large and above</div>
<p>After</p>
```

This works as expected at https://play.tailwindcss.com/, so it seems to be an issue with WindiCSS and/or the preprocessor.

**Comment by alexanderniebuhr** [comment]
cannot reproduce. it might the combination of svelte-kit and vite. please try [vite plugin](https://github.com/windicss/vite-plugin-windicss) instead of preprocessor

**Comment by alexanderniebuhr** [comment]
might be related to #82 
can you also try [v3.1.3](https://github.com/windicss/svelte-windicss-preprocess/releases/tag/v3.1.3)

**Comment by pikeas** [comment]
I've updated all packages and cleared the `.svelte` folder, same issue. 

On further testing, it's a bit quirky: it seems to only fail when placed in `$layout.svelte`:

- When placed only in `routes/$layout.svelte` (after `<slot>`), it works for S and L, fails for M and XL.
- When placed in both `routes/$layout.svelte` and `routes/index.svelte`, both divs work for all breakpoints.
- When placed only in `routes/index.svelte`, it works for all breakpoints.
- When placed only in `foo/Bar.svelte`, it works for all breakpoints.

It's pretty bizarre that

**Comment by alexanderniebuhr** [comment]
for svelte-kit check out [vite-plugin-windicss](https://github.com/windicss/vite-plugin-windicss)

**Comment by pikeas** [comment]
> for svelte-kit check out [vite-plugin-windicss](https://github.com/windicss/vite-plugin-windicss)

`import "virtual:windi.css"` doesn't seem to work in `$layout.svelte` - where should this go?

**Comment by alexanderniebuhr** [comment]
https://github.com/alexanderniebuhr/sveltekit-vite-windicss/blob/684fb769c5240eae914cad710972eeca171eb537/src/routes/%24layout.svelte#L2

**Comment by pikeas** [comment]
Thanks for the quick reply! That works and seems to have resolved the issue - `hidden/block` are now working at all breakpoints, even when only used in `$layout.svelte`.

However, this only seems to work for the default breakpoints:

```
//tailwind.config.cjs

module.exports = {
    theme: {
        screens: {
            "3xl": "1920px",
        },
    },
```

`3xl:hidden` isn't being picked up as a class.

**Comment by alexanderniebuhr** [comment]
you want to extend theme instead of overriding I guess

```
module.exports = {
  theme: {
    extend: {
      // Adds a new breakpoint in addition to the default breakpoints
      screens: {
        '3xl': '1600px',
      }
    }
  }
}
```

**Comment by pikeas** [comment]
I cleaned up my config when sharing it here and accidentally changed the semantics. In my actual config, I'm using `extend` and finding that WindiCSS isn't picking it up per above.

**Comment by alexanderniebuhr** [comment]
need to validate that with our setup later..

**Comment by alexanderniebuhr** [comment]
@pikeas i actually cannot reproduce it. it works, for me. are you sure on the latest update?
