### ISSUE TITLE
important config breaks @apply

### ISSUE THREAD

**Issue by mrwokkel** [windicss/svelte-windicss-preprocess#93]
When in config:
```
{
  important: '.wnd',
  ...
}
```
windi classes are al scoped in `.wnd` but
`@apply` 'returns' nothing.

without the important config `@apply` works as expected.

**Comment by alexanderniebuhr** [comment]
Have to check later..

**Comment by alexanderniebuhr** [comment]
Is this svelte or sveltekit?

**Comment by mrwokkel** [comment]
The issue is with svelte-windicss-preprocess and sveltekit. 

Was using the `npx svelte-add windicss` which is using svelte-windicss-preprocess instead of vite-plugin-windicss.

**Comment by alexanderniebuhr** [comment]
👍 then we do suggest using vite-plugin-windicss for svelte-kit for now

**Comment by mrwokkel** [comment]
Yes. I also added a [comment](https://github.com/svelte-add/windicss/issues/1#issuecomment-811005417) to the svelte-add repo, hopefully preventing more issues here.

**Comment by alexanderniebuhr** [comment]
#65
