### ISSUE TITLE
Interferes with on:load of script inside svelte:head in sapper

### ISSUE THREAD

**Issue by mishrasatyam** [windicss/svelte-windicss-preprocess#96]
Framework : Sapper 
When I am loading some cdn in svelte:head and using on:load function along with it :

eg:
```
<svelte:head>
	<script src="https://cdn.plot.ly/plotly-latest.min.js" on:load={()=>{alert(1)}}></script>
</svelte:head>
```
I get following error:

```
✗ server
Unexpected token
  1 | <svelte:head>
> 2 |   <script src="https://cdn.plot.ly/plotly-latest.min.js" on:load={()= ✂prettier:content✂="e2FsZXJ0KDEpfX0+">{}</script>
    |                   
```

**Comment by alexanderniebuhr** [comment]
we did drop support for sapper. but what you can do is setting following javascript process.env
`process.env.BROWSER = true`

**Comment by alexanderniebuhr** [comment]
also might be releaded to https://github.com/sveltejs/prettier-plugin-svelte/issues/196
