### ISSUE TITLE
Latest versions break multiline classes but works with `2.3.1`. Reproduction repo included.

### ISSUE THREAD

**Issue by sebastiangug** [windicss/svelte-windicss-preprocess#99]
I have cloned the example rollup project in this repo to test if defining classes over multiple lines works. 

Repo link: https://github.com/sebastiangug/svelte-windicss-preprocess-bug-reproduction

just run `pnpm i` and then `pnpm dev` to start the server

I have found it does not work with the latest versions, but works with `2.3.1` so something must've broken. 

Component added in Widget.svelte

```
  <button class="
  bg-blue-500
   p-4 
   text-white">TEST BUTTON</button>
``` 

which when using 2.3.1 results in: 

![image](https://user-images.githubusercontent.com/27768313/113507018-ee64e500-953f-11eb-838d-3defe6482f15.png)

But when using `3.2.0` produces this: 

![image](https://user-images.githubusercontent.com/27768313/113507030-0b011d00-9540-11eb-8627-18b2b56ffa85.png)

**Comment by alexanderniebuhr** [comment]
Super strange I have another person having this issue.. but I cannot reproduce it :(

**Comment by sebastiangug** [comment]
Try to clone the repo above

**Comment by alexanderniebuhr** [comment]
@sebastiangug check this PR. merge it and run `pnpm dev`.. copy and paste full output of terminal!!
https://github.com/sebastiangug/svelte-windicss-preprocess-bug-reproduction/pull/1

**Comment by IRediTOTO** [comment]
i have this error too. :\ Don't know why :) 
This is result when use 2.3.1
![image](https://user-images.githubusercontent.com/15695252/114242798-af0e1c80-99b5-11eb-9a5f-b8cbc37079b9.png)
And this is newest version. When i `run dev` everything fine, but on run build look like tailwind base wasnt loaded. I use svelte kit. 
![image](https://user-images.githubusercontent.com/15695252/114242822-bb927500-99b5-11eb-9144-b4d281459d4f.png)
I turn on debug mode and get this
```
[DEBUG] mainfile: false
[DEBUG] filename: E:/Hoctap/Nodejs/Svelte - Sapper/svelte-kit/src/routes/about.svelte
[DEBUG] called preprocessor
[DEBUG] production, child file, no preflights
[DEBUG] mainfile: false
[DEBUG] filename: E:/Hoctap/Nodejs/Svelte - Sapper/svelte-kit/src/routes/index.svelte
[DEBUG] called preprocessor
[DEBUG] production, child file, no preflights
[DEBUG] mainfile: false
```

**Comment by alexanderniebuhr** [comment]
@IRediTOTO use kit: true

**Comment by IRediTOTO** [comment]
> @IRediTOTO use `kit: true` and `mode: dev`

You mean this config? It not work
```
preprocess: [
		require('svelte-windicss-preprocess').preprocess({
			config: "tailwind.config.cjs",
			kit:true,
			mode:"dev",
			debug: true,
		})
	],
```

**Comment by alexanderniebuhr** [comment]
Strange. Since you are using sapper we do not support this directly. If you give your repo I can take a quick look

**Comment by IRediTOTO** [comment]
> Strange. Since you are using svelte kit we do not support this directly. If you give your repo I can take a quick look.
> Also you might try vite-windicss-plugin for svelte kit

Here is it: https://github.com/IRediTOTO/learn-svelte-kit
I will work fine with version 2.3.1

**Comment by alexanderniebuhr** [comment]
@IRediTOTO i know the issue, and will make a fix for you

**Comment by alexanderniebuhr** [comment]
you guys can update to [v3.3.2](https://github.com/windicss/svelte-windicss-preprocess/releases/tag/v3.3.2) and set your options for kit as following (you can add other options if you need, like devTools or config)

```
		require('svelte-windicss-preprocess').preprocess({
			kit: true,
			mode: "dev",
			silent: false,
			debug: false
		})
```

**Comment by IRediTOTO** [comment]
> you guys can update to [v3.3.2](https://github.com/windicss/svelte-windicss-preprocess/releases/tag/v3.3.2) and set your options for kit as following (you can add other options if you need, like devTools or config)
> 
> ```
> 		require('svelte-windicss-preprocess').preprocess({
> 			kit: true,
> 			mode: "dev",
> 			silent: false,
> 			debug: false
> 		})
> ```

thank you look like it work.

**Comment by alexanderniebuhr** [comment]
@IRediTOTO still if you want more mature implementation with svelte-kit, we do have https://github.com/windicss/vite-plugin-windicss

**Comment by IRediTOTO** [comment]
> @IRediTOTO still if you want more mature implementation with svelte-kit, we do have https://github.com/windicss/vite-plugin-windicss

i knew it and waiting for full featured like this pack :D Thank you

**Comment by sebastiangug** [comment]
This can be closed as far as I'm concerned, I've started using vite as I wanted to use that already rather than rollup for various reasons, so now I'm mostly working with the vite-plugin that alexander has tagged above. 

Good luck & thank you!
